name: LabyUtils
version: '${project.version}'
main: com.rappytv.labyutils.LabyUtilsPlugin
api-version: '1.13'
authors: [ RappyTV ]
description: A simple plugin to utilize LabyMod's server API without coding knowledge.
softdepend:
  - Vault
  - PlaceholderAPI

permissions:
  labyutils.reload:
    description: Lets the player reload the config with /labyutils
    default: op

commands:
  labyutils:
    permission: labyutils.reload
    description: Reloads the plugin config