name: LabyUtils
version: '${project.version}'
main: com.rappytv.labyutils.bukkit.LabyUtilsBukkit
api-version: '1.13'
authors: [ RappyTV ]
description: A simple plugin to utilize LabyMod's server API without coding knowledge.
softdepend:
  - Vault
  - PlaceholderAPI

permissions:
  labyutils.bypass.addon.*:
    default: op
    description: Ignores any recommended, required, or disallowed addons
  labyutils.bypass.labymod:
    default: op
    description: Lets the player join with LabyMod when it's disallowed
  labyutils.info:
    default: op
    description: Lets the player use /labyinfo
  labyutils.info.subtitle:
    default: op
    description: Lets the player see a player's server subtitle with /labyinfo
  labyutils.info.economy:
    default: op
    description: Lets the player see a player's economy balances with /labyinfo
  labyutils.info.version:
    default: op
    description: Lets the player see a player's LabyMod version with /labyinfo
  labyutils.info.region:
    default: op
    description: Lets the player see a player's region with /labyinfo
  labyutils.permissions.*:
    default: op
    description: Gives the player all configured LabyMod permissions
  labyutils.reload:
    default: op
    description: Lets the player reload the config with /labyutils
  labyutils.voice:
    default: op
    description: Gives access to the VoiceChat command
  labyutils.voice.mute.permanent:
    default: op
    description: Lets the player mute other players permanently
  labyutils.voice.mute.temporary:
    default: op
    description: Lets the player mute other players temporarily
  labyutils.voice.unmute:
    default: op
    description: Lets the player unmute other players

commands:
  labyinfo:
    description: Shows LabyMod specific info about a player
    permission: labyutils.info
  labyutils:
    description: Reloads the plugin config
    permission: labyutils.reload
  labyvoice:
    description: Lets you mute or unmute players in VoiceChat
    permission: labyutils.voice
